---

- import_playbook: common.yml
  tags:
    - common
- import_playbook: desktop.yml
  tags:
    - desktop
- import_playbook: development.yml
  tags:
    - development

- name: Ubuntu Desktop Playbook
  hosts: localhost
