---
- name: Add TimeShift repository 
  apt_repository: 
    repo: ppa:teejee2008/ppa
    state: present

- name: Install TimeShift OS Snapshot tool and BTRFS
  apt:
    pkg:
      - timeshift
#    - btrfs-tools
    state: present
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"