---


- name: Add GPG apt Key
  apt_key:
    url: https://nextcloud.com/nextcloud.asc
    state: present

- name: Add Nextcloud PPA repository
  apt_repository:
    repo: ppa:nextcloud-devs/client
    state: present

- name: Install Nextcloud Desktop Sync App
  apt:
    pkg: ["nextcloud-desktop", "nautilus-nextcloud"]
    state: present
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
