---
    - name: Install packages
      ansible.builtin.apt:
        name: ffmpeg
        state: latest
        update_cache: true

   #get youtube-dl
    - name: Download from source move to executables folder and set permissions
      get_url:
        url: http://yt-dl.org/latest/youtube-dl
        dest: "{{ youtubedl_executable_path }}"
        mode: 0755
        force: yes

